---
title: "Harry Potter Characters"
author: "Peter Menzies"
date: "9/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
hp_characters <- read_delim(here("harry_potter_characters.csv"), delim = ';', na = '', trim_ws = TRUE)

names(hp_characters)

unique(hp_characters$Wand)

hp_characters <- janitor::clean_names(hp_characters)

## function to trim leading whitespace - arguments in sub are a regular expression indicating leading whitespace,
## the value to replace them with, and the vector that it's being applied to

trim.leading <- function(x) {
  
 sub("^\\s+", "", x)

}
  
wands <- hp_characters %>%
  select(name, wand) %>%
  filter(wand != "Unknown") %>% 
  separate(wand, into = c("wand_length", "wand_type"), sep = '"') %>% 
  filter(wand_type != "NA") %>% 
  filter(str_detect(wand_type, pattern = ",", negate = TRUE)) %>% 
  filter(str_detect(wand_type, pattern = "Unknown", negate = TRUE)) %>% 
  filter(str_detect(wand_type, pattern = "unknown", negate = TRUE)) %>% 
  mutate(wand_type = trim.leading(wand_type)) #%>% 
  #separate(wand_type, into = c("wand_wood", "wand_core"), sep = " ")
  

wands_numeric <- wands %>% 
  mutate(wand_length = str_replace_all(wand_length, c("¼" = ".25", "½" = ".5", "¾" = ".75"))) %>% 
  mutate(wand_length = as.numeric(wand_length))

wands_main <- wands_numeric %>% 
  filter(name %in% wands_numeric$name[c(1,2,3,4,5,6,7,9,12,13,14,17)]) 


wands_plot <- ggplot(wands_main, aes(x = name, y = wand_length)) +
  geom_col()

wands_plot

```

